CONFIG = "config.json"

HOST = "localhost"
PORT = 9200
AUTH = ("admin", "admin")  # For testing only. Don't store credentials in code.

datafile_fields = [
    "query",
    "id",
    "timestamp_utc",
    "local_time",
    "user_screen_name",
    "text",
    "possibly_sensitive",
    "retweet_count",
    "like_count",
    "reply_count",
    "impression_count",
    "lang",
    "to_username",
    "to_userid",
    "to_tweetid",
    "source_name",
    "source_url",
    "user_location",
    "lat",
    "lng",
    "user_id",
    "user_name",
    "user_verified",
    "user_description",
    "user_url",
    "user_image",
    "user_tweets",
    "user_followers",
    "user_friends",
    "user_likes",
    "user_lists",
    "user_created_at",
    "user_timestamp_utc",
    "collected_via",
    "match_query",
    "retweeted_id",
    "retweeted_user",
    "retweeted_user_id",
    "retweeted_timestamp_utc",
    "quoted_id",
    "quoted_user",
    "quoted_user_id",
    "quoted_timestamp_utc",
    "collection_time",
    "url",
    "place_country_code",
    "place_name",
    "place_type",
    "place_coordinates",
    "links",
    "domains",
    "media_urls",
    "media_files",
    "media_types",
    "media_alt_texts",
    "mentioned_names",
    "mentioned_ids",
    "hashtags",
]

datafile_properties = {
    "collected_via": {"type": "keyword"},
    "collection_time": {"type": "keyword", "index": False},
    "domains": {"type": "keyword"},
    "hashtags": {"type": "keyword"},
    "id": {"type": "keyword"},
    "impression_count": {"type": "integer"},
    "lang": {"type": "keyword"},
    "lat": {"type": "float"},
    "like_count": {"type": "integer"},
    "links": {
        "type": "text",
        "fields": {"keyword": {"type": "keyword", "ignore_above": 280}},
    },
    "links_to_resolve": {"type": "boolean"},
    "lng": {"type": "float"},
    "local_time": {"type": "keyword", "index": False},
    "match_query": {"type": "boolean"},
    "media_files": {"type": "keyword", "index": False},
    "media_types": {"type": "keyword"},
    "media_urls": {"type": "keyword", "index": False},
    "media_alt_texts": {"type": "text", "analyzer": "standard"},
    "mentioned_ids": {"type": "keyword"},
    "mentioned_names": {"type": "keyword"},
    "place_coordinates": {"type": "float", "index": False},
    "place_country_code": {"type": "keyword"},
    "place_name": {"type": "text", "fields": {"keyword": {"type": "keyword"}}},
    "place_type": {"type": "keyword"},
    "possibly_sensitive": {"type": "boolean"},
    "proper_links": {
        "type": "text",
        "fields": {"keyword": {"type": "keyword", "ignore_above": 280}},
    },
    "query": {"type": "keyword"},
    "quoted_id": {"type": "keyword"},
    "quoted_timestamp_utc": {"type": "date", "format": "epoch_second"},
    "quoted_user": {"type": "keyword"},
    "quoted_user_id": {"type": "keyword"},
    "reply_count": {"type": "integer"},
    "retweet_count": {"type": "integer"},
    "retweeted_id": {"type": "keyword"},
    "retweeted_timestamp_utc": {"type": "date", "format": "epoch_second"},
    "retweeted_user": {"type": "keyword"},
    "retweeted_user_id": {"type": "keyword"},
    "source_name": {"type": "keyword", "ignore_above": 80},
    "source_url": {"type": "keyword", "ignore_above": 80},
    "text": {"type": "text", "analyzer": "standard"},
    "timestamp_utc": {"type": "date", "format": "epoch_second"},
    "to_tweetid": {"type": "keyword"},
    "to_userid": {"type": "keyword"},
    "to_username": {"type": "keyword"},
    "url": {"type": "text", "index": False},
    "user_created_at": {"type": "keyword", "index": False},
    "user_timestamp_utc": {"type": "date", "format": "epoch_second"},
    "user_description": {"type": "text", "analyzer": "standard"},
    "user_followers": {"type": "integer"},
    "user_friends": {"type": "integer"},
    "user_id": {"type": "keyword"},
    "user_image": {"type": "text", "index": False},
    "user_lang": {"type": "keyword"},
    "user_likes": {"type": "integer"},
    "user_lists": {"type": "integer"},
    "user_location": {
        "type": "text",
        "fields": {"keyword": {"type": "keyword", "ignore_above": 80}},
    },
    "user_name": {"type": "keyword"},
    "user_screen_name": {"type": "keyword"},
    "user_tweets": {"type": "integer"},
    "user_url": {
        "type": "text",
        "fields": {"keyword": {"type": "keyword", "ignore_above": 280}},
    },
    "user_verified": {"type": "boolean"},
}


nlp_properties = {
    "text_tokenized": {"type": "array"},
    "tokens": {"type": "nested"},
    "dependencies": {"type": "nested"},
    "corefs": {"type": "nested"},
    "openieTriples": {"type": "nested"},
    "entityMentions": {"type": "nested"},
}

properties = datafile_properties.update(nlp_properties)

INDEX_BODY = {
    "settings": {"index": {"number_of_shards": 4}},
    "mappings": {"properties": properties},
}
